# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: true

r:
  - devel

before_install:
  - Rscript -e 'if (length(find.package("devtools", quiet = TRUE)) == 0) install.packages("devtools")'
- Rscript -e 'devtools::install_deps()'

notifications:
  slack:
  on_success: change
on_failure: change
